# **GETTING STARTED**
1. Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/
2. Pytorch Docs: https://pytorch.org/docs/stable/index.html
3. Domain specific docs: https://pytorch.org/pytorch-domains




In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


# Introduction to Tensors
https://pytorch.org/docs/stable/tensors.html

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

#Get number out of tensor (make int)
scalar.item()

#Tensor rank 1
vector = torch.tensor([7,7])
vector.ndim

#Tensor rank 2
tensor_rank2 = torch.tensor([[7,8],[9,10]])
tensor_rank2.ndim

tensor_rank2.shape

torch.Size([2, 2])

### Random Tensors
Why random tensors? Cuz many NNs start with random tensors and then change them to better represent the data.

In [ ]:

#Generate a random tensor
random_tensor = torch.rand(3,4)
random_tensor

zeros = torch.zeros(size = (3,4))
zeros*random_tensor

ones = torch.ones(size = (4,5))

#datatype of numbers in ones
ones.dtype

torch.float32

In [ ]:
#Range of Tensors
torch.arange(0,10)
torch.arange(start=0,end=10,step=3)

#Replicating shape
torch.zeros_like(input=tensor_rank2)

tensor([[0, 0],
        [0, 0]])

### **Tensor datatypes**
Most common errors you'll get for Tensors
1. Tensor datatype not right
2. Tensor shape not right
3. Tensors not on right device

In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,          # Datatype of the tensor elements
                               device=None,         # By default this is cpu : Use cuda for GPU
                               requires_grad=False) # Whether or not to track gradients with this tensor operations
float_32_tensor.shape

torch.Size([3])

In [ ]:
float_32_tensor.dtype #float32

float_16tensor = float_32_tensor.type(torch.float16)
float_16tensor

torch.float32

### **Getting Information from tensors**



In [ ]:
some_tensor = torch.rand(size = (3,4))
some_tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")                      #  Alternative :: some_tensor.size()
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.1972, 0.1019, 0.1537, 0.4374],
        [0.5061, 0.0753, 0.8291, 0.2802],
        [0.2240, 0.1800, 0.1659, 0.0773]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


### **Tensor Operations**
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [ ]:
my_tensor = torch.rand(5)   #Tensor with 5 elements
my_tensor.add_(5)
my_tensor + 10
print(my_tensor - 5)
print(torch.mul(my_tensor, 10))
#my_tensor / 10
my_tensor

tensor2 = torch.tensor([1,2,3,4,5])
print(f"Tensor1: {my_tensor}")
print(f"Tensor2: {tensor2}")
print(f"Tensor1 * Tensor2: {my_tensor * tensor2}")

print(tensor2.dtype)

#change datatype of elements of my_tensor to int64
my_tensor = my_tensor.type(torch.int64)
print(my_tensor)
#convert "my_tensor to int" and perform matmul
torch.matmul(my_tensor, tensor2)

tensor([0.1517, 0.0764, 0.3335, 0.9770, 0.9954])
tensor([51.5169, 50.7635, 53.3349, 59.7699, 59.9537])
Tensor1: tensor([5.1517, 5.0764, 5.3335, 5.9770, 5.9954])
Tensor2: tensor([1, 2, 3, 4, 5])
Tensor1 * Tensor2: tensor([ 5.1517, 10.1527, 16.0005, 23.9080, 29.9769])
torch.int64
tensor([5, 5, 5, 5, 5])


tensor(75)

### **Tensor aggregations** : Min, Max, Sum etc

In [ ]:
tensor = torch.arange(start = 0, end = 100, step = 10)
tensor

torch.min(tensor), torch.max(tensor)
torch.mean(tensor.type(torch.float32))        # does not work with long datatypes, use floating

torch.sum(tensor), torch.prod(tensor)

#positional min max
tensor.argmin(), tensor.argmax()

(tensor(0), tensor(9))

### **Reshaping, Stacking, Squeezing and UnSqueezing (Tensors)**


*   Reshaping - convert from one shape to other
*   View - Return a view of input tensor of certain shape but keep the same memory as the input tensor
* Stacking - Combine multiple tensors on top(Vstack), sidebyside(Hstack)
* Squeezing - removes 1 dimension from tensor
* Permute - Return a view of input tensor with dimensions swapped in certain way







In [ ]:
import torch
x = torch.arange(1.0, 8.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

x_reshaped = x.reshape(7,1)
x_reshaped, x_reshaped.shape

#Keep the size same and redistribute the existing in the dimensions you want

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.]]),
 torch.Size([7, 1]))

In [ ]:
z = x.view(1,7)
z, z.shape

z[:, 0] = 5
x, z

(tensor([5., 2., 3., 4., 5., 6., 7.]), tensor([[5., 2., 3., 4., 5., 6., 7.]]))

In [ ]:
#stack on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
print(x_stacked)

#stack side by side
x_stacked = torch.stack([x,x,x,x], dim = 1)
print(x_stacked)

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])
tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])


In [ ]:
#Squeezing tensors
x_reshaped = x.reshape(1,7)
x_squeezed = x_reshaped.squeeze()

print(x_reshaped, x_reshaped.shape)
x_squeezed, x_squeezed.shape

tensor([[5., 2., 3., 4., 5., 6., 7.]]) torch.Size([1, 7])


RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 1 is not equal to len(dims) = 2

In [ ]:
#indexing on a tensor
tensor = torch.arange(1,10).reshape(1,3,3)
tensor, tensor.shape

print(tensor[0][0][2])
print(tensor[0,0,2])
print(tensor[0,:,:])

tensor(3)
tensor(3)
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### **Interact with NumPy**
1. Tensor to Numpy -> *torch.Tensor.numpy()*
2. Numpy to Tensor -> *torch.from_numpy(ndarray)*

### **Reproducibility**
  Trying to take random out of random

  Neural networks learn: random nums -> tensorOps -> update nums to get better representation of the data -> again -> again...
  To reduce randomness in neural networks we use **random seed**

In [4]:
import torch
random_tensorA = torch.rand(3,4)
random_tensorB = torch.rand(3,4)

print(random_tensorA)
print(random_tensorB)
print(random_tensorA == random_tensorB)

#Lets set a random seed to induce a randomness with specific entropy
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensorC = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensorD = torch.rand(3,4)

print(random_tensorC)
print(random_tensorD)
print(random_tensorC == random_tensorD)

tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])
tensor([[0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [1]:
#Running pytorch objects on GPU
# GPUs allow faster execution

!nvidia-smi

Sat Jul  6 15:30:02 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
device

torch.cuda.device_count()

1

In [6]:
#Create a tensor(default on CPU)
tensor = torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor, tensor.device)

#Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [ ]:
# Number 3 error: error of device [numpy doesnt run on gpu]
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

## **Something Extra N Some exercises**

In [15]:
tensor = torch.rand(7,7)
tensor

tensor2 = torch.rand(1,7)
tensor2 = torch.transpose(tensor2, 0, 1)

torch.matmul(tensor, tensor2) #matrix multiplication


#NExt ASSIGNMENT
RANDOM_SEED = 123
torch.manual_seed(RANDOM_SEED)

rand_tensor = torch.rand(2,1)
rand_tensor

tensor([[0.2961],
        [0.5166]])